name: "CMake - Linux-GCC"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  BUILD_TYPE: Release
  CC: gcc
  CXX: g++

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Update compilers
      shell: bash
      run: |
        sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
        sudo apt-get -yq install g++ gcc

    - name: Configure CMake
      shell: bash
      run: |
        cmake . -Btests -G "Unix Makefiles"
    - name: Build
      shell: bash
      run: |
        cd tests
        make

    - name: Test
      shell: bash
      run: |
        ./tests/testc
