name: "CMake - Linux-GCC"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  BUILD_TYPE: Release
  CC: gcc-8
  CXX: g++-8

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Update compilers
      shell: bash
      run: |
        sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
        sudo apt-get -yq install g++-8 gcc-8

    - name: Configure CMake
      shell: bash
      run: |
        cd tests && mkdir build
        cmake -Bbuild -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX
 
    - name: Build
      shell: bash
      run: |
        cd tests
        cmake --build build --config $BUILD_TYPE

    - name: Test
      shell: bash
      run: |
        ./tests/build/utf8d_test_c
