name: "CMake - Linux-Clang"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  BUILD_TYPE: Release
  CC: clang
  CXX: clang++

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Update compilers
      shell: bash
      run: |
        sudo apt-get install clang lld libc++-dev libc++abi-dev clang-tools

    - name: Configure CMake
      shell: bash
      run: |
        cmake -Btests -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX

    - name: Build
      shell: bash
      run: |
        cd tests
        cmake --build . --config $BUILD_TYPE

    - name: Test
      shell: bash
      run: |
        ./tests/testc