name: "CMake - MSVC"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  BUILD_TYPE: Release
  CC: cl
  CXX: cl

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        config:
        - {
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
          }

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Configure CMake
      shell: bash
      run: |
        cd tests && mkdir build
        cmake -Bbuild -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX

    - name: Build
      shell: bash
      run: |
        cd tests
        cmake --build build --config $BUILD_TYPE

    - name: Test
      shell: bash
      run: |
        ./tests/build/Release/utf8d_test_c.exe
